//// <auto-generated />
//using System;
//using BMW_ONBOARDING_SYSTEM.Models;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//namespace BMW_ONBOARDING_SYSTEM.Migrations
//{
//    [DbContext(typeof(INF370DBContext))]
//    [Migration("20210819125013_AddedTableUser")]
//    partial class AddedTableUser
//    {
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "3.1.0")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128)
//                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.Achievement", b =>
//                {
//                    b.Property<DateTime?>("AchievementDate")
//                        .HasColumnType("datetime");

//                    b.Property<int>("AchievementId")
//                        .HasColumnName("AchievementID")
//                        .HasColumnType("int");

//                    b.Property<int?>("AchievementTypeId")
//                        .HasColumnName("AchievementTypeID")
//                        .HasColumnType("int");

//                    b.Property<int?>("CourseId")
//                        .HasColumnName("CourseID")
//                        .HasColumnType("int");

//                    b.Property<decimal?>("MarkAchieved")
//                        .HasColumnType("decimal(18, 0)");

//                    b.Property<int?>("OnboarderId")
//                        .HasColumnName("OnboarderID")
//                        .HasColumnType("int");

//                    b.Property<int?>("QuizId")
//                        .HasColumnName("QuizID")
//                        .HasColumnType("int");

//                    b.ToTable("Achievement");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.AchievementType", b =>
//                {
//                    b.Property<int>("AchievementTypeId")
//                        .HasColumnName("AchievementTypeID")
//                        .HasColumnType("int");

//                    b.Property<string>("AchievementTypeDescription")
//                        .HasColumnType("nvarchar(50)")
//                        .HasMaxLength(50);

//                    b.Property<int?>("BadgeId")
//                        .HasColumnName("BadgeID")
//                        .HasColumnType("int");

//                    b.HasKey("AchievementTypeId");

//                    b.HasIndex("BadgeId");

//                    b.ToTable("AchievementType");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.ArchiveStatus", b =>
//                {
//                    b.Property<int>("ArchiveStatusId")
//                        .HasColumnName("ArchiveStatusID")
//                        .HasColumnType("int");

//                    b.Property<string>("ArchieveStatusDescription")
//                        .HasColumnType("varchar(50)")
//                        .HasMaxLength(50)
//                        .IsUnicode(false);

//                    b.HasKey("ArchiveStatusId");

//                    b.ToTable("ArchiveStatus");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.Badge", b =>
//                {
//                    b.Property<int>("BadgeId")
//                        .HasColumnName("BadgeID")
//                        .HasColumnType("int");

//                    b.Property<string>("BadgeDecription")
//                        .HasColumnType("varchar(50)")
//                        .HasMaxLength(50)
//                        .IsUnicode(false);

//                    b.HasKey("BadgeId");

//                    b.ToTable("Badge");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.Certificate", b =>
//                {
//                    b.Property<int>("CertificateId")
//                        .HasColumnName("CertificateID")
//                        .HasColumnType("int");

//                    b.Property<DateTime?>("CertificateDateGenerated")
//                        .HasColumnType("datetime");

//                    b.Property<string>("CertificateDescription")
//                        .HasColumnType("varchar(50)")
//                        .HasMaxLength(50)
//                        .IsUnicode(false);

//                    b.Property<int?>("CertificateTypeId")
//                        .HasColumnName("CertificateTypeID")
//                        .HasColumnType("int");

//                    b.Property<int?>("CourseCompletionStatusId")
//                        .HasColumnName("CourseCompletionStatusID")
//                        .HasColumnType("int");

//                    b.Property<int?>("LessonCompletionStatusId")
//                        .HasColumnName("LessonCompletionStatusID")
//                        .HasColumnType("int");

//                    b.HasKey("CertificateId");

//                    b.ToTable("Certificate");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.CertificateType", b =>
//                {
//                    b.Property<int>("CertificateTypeId")
//                        .HasColumnName("CertificateTypeID")
//                        .HasColumnType("int");

//                    b.Property<string>("CertificateTypeTemplate")
//                        .HasColumnType("varchar(50)")
//                        .HasMaxLength(50)
//                        .IsUnicode(false);

//                    b.HasKey("CertificateTypeId");

//                    b.ToTable("CertificateType");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.Course", b =>
//                {
//                    b.Property<int>("CourseId")
//                        .HasColumnName("CourseID")
//                        .HasColumnType("int");

//                    b.Property<string>("CourseDescription")
//                        .HasColumnType("varchar(50)")
//                        .HasMaxLength(50)
//                        .IsUnicode(false);

//                    b.Property<DateTime?>("CourseDueDate")
//                        .HasColumnType("datetime");

//                    b.Property<string>("CourseName")
//                        .HasColumnType("varchar(50)")
//                        .HasMaxLength(50)
//                        .IsUnicode(false);

//                    b.HasKey("CourseId");

//                    b.ToTable("Course");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.CourseCompletionStatus", b =>
//                {
//                    b.Property<DateTime?>("CourseCompletionStatusDate")
//                        .HasColumnType("date");

//                    b.Property<string>("CourseCompletionStatusDescription")
//                        .HasColumnType("varchar(50)")
//                        .HasMaxLength(50)
//                        .IsUnicode(false);

//                    b.Property<int>("CourseCopletionStatusId")
//                        .HasColumnName("CourseCopletionStatusID")
//                        .HasColumnType("int");

//                    b.Property<int?>("CourseId")
//                        .HasColumnName("CourseID")
//                        .HasColumnType("int");

//                    b.Property<int?>("OnboarderId")
//                        .HasColumnName("OnboarderID")
//                        .HasColumnType("int");

//                    b.ToTable("CourseCompletionStatus");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.Department", b =>
//                {
//                    b.Property<int>("DepatmentId")
//                        .HasColumnName("DepatmentID")
//                        .HasColumnType("int");

//                    b.Property<string>("DepartmentDescription")
//                        .HasColumnType("varchar(50)")
//                        .HasMaxLength(50)
//                        .IsUnicode(false);

//                    b.HasKey("DepatmentId");

//                    b.ToTable("Department");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.Employee", b =>
//                {
//                    b.Property<int>("EmployeeId")
//                        .HasColumnName("EmployeeID")
//                        .HasColumnType("int");

//                    b.Property<int?>("AddressId")
//                        .HasColumnName("AddressID")
//                        .HasColumnType("int");

//                    b.Property<decimal?>("ContactNumber")
//                        .HasColumnType("numeric(18, 0)");

//                    b.Property<int?>("DepartmentId")
//                        .HasColumnName("DepartmentID")
//                        .HasColumnType("int");

//                    b.Property<string>("EmailAddress")
//                        .HasColumnType("varchar(50)")
//                        .HasMaxLength(50)
//                        .IsUnicode(false);

//                    b.Property<int?>("EmployeeCalendarId")
//                        .HasColumnName("EmployeeCalendarID")
//                        .HasColumnType("int");

//                    b.Property<string>("EmployeeJobTitle")
//                        .HasColumnType("varchar(50)")
//                        .HasMaxLength(50)
//                        .IsUnicode(false);

//                    b.Property<string>("FirstName")
//                        .HasColumnType("varchar(50)")
//                        .HasMaxLength(50)
//                        .IsUnicode(false);

//                    b.Property<int?>("GenderId")
//                        .HasColumnName("GenderID")
//                        .HasColumnType("int");

//                    b.Property<decimal?>("Idnumber")
//                        .HasColumnName("IDNumber")
//                        .HasColumnType("numeric(18, 0)");

//                    b.Property<string>("LastName")
//                        .HasColumnType("varchar(50)")
//                        .HasMaxLength(50)
//                        .IsUnicode(false);

//                    b.Property<string>("MiddleName")
//                        .HasColumnType("varchar(50)")
//                        .HasMaxLength(50)
//                        .IsUnicode(false);

//                    b.Property<int?>("TitleId")
//                        .HasColumnName("TitleID")
//                        .HasColumnType("int");

//                    b.HasKey("EmployeeId");

//                    b.HasIndex("DepartmentId");

//                    b.HasIndex("EmployeeCalendarId");

//                    b.HasIndex("GenderId");

//                    b.HasIndex("TitleId");

//                    b.ToTable("Employee");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.EmployeeCalendar", b =>
//                {
//                    b.Property<int>("EmployeeCalendarId")
//                        .HasColumnName("EmployeeCalendarID")
//                        .HasColumnType("int");

//                    b.Property<string>("EmployeeCalendarLink")
//                        .HasColumnType("varchar(200)")
//                        .HasMaxLength(200)
//                        .IsUnicode(false);

//                    b.HasKey("EmployeeCalendarId");

//                    b.ToTable("EmployeeCalendar");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.Gender", b =>
//                {
//                    b.Property<int>("GenderId")
//                        .HasColumnName("GenderID")
//                        .HasColumnType("int");

//                    b.Property<string>("GenderDescription")
//                        .HasColumnType("varchar(50)")
//                        .HasMaxLength(50)
//                        .IsUnicode(false);

//                    b.HasKey("GenderId");

//                    b.ToTable("Gender");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.Lesson", b =>
//                {
//                    b.Property<int>("LessonId")
//                        .HasColumnName("LessonID")
//                        .HasColumnType("int");

//                    b.Property<int?>("CourseId")
//                        .HasColumnName("CourseID")
//                        .HasColumnType("int");

//                    b.Property<int?>("LessonCompletionStatusId")
//                        .HasColumnName("LessonCompletionStatusID")
//                        .HasColumnType("int");

//                    b.Property<string>("LessonDescription")
//                        .HasColumnType("varchar(50)")
//                        .HasMaxLength(50)
//                        .IsUnicode(false);

//                    b.Property<string>("LessonName")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("LessonId");

//                    b.HasIndex("CourseId");

//                    b.HasIndex("LessonCompletionStatusId");

//                    b.ToTable("Lesson");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.LessonCompletionStatus", b =>
//                {
//                    b.Property<int>("LessonCompletionStatusId")
//                        .HasColumnName("LessonCompletionStatusID")
//                        .HasColumnType("int");

//                    b.Property<DateTime?>("LessonCompletionDate")
//                        .HasColumnType("datetime");

//                    b.Property<string>("LessonCompletionStatusDescription")
//                        .HasColumnType("varchar(50)")
//                        .HasMaxLength(50)
//                        .IsUnicode(false);

//                    b.HasKey("LessonCompletionStatusId");

//                    b.ToTable("LessonCompletionStatus");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.LessonContent", b =>
//                {
//                    b.Property<int>("LessonConentId")
//                        .HasColumnName("LessonConentID")
//                        .HasColumnType("int");

//                    b.Property<int?>("ArchiveStatusId")
//                        .HasColumnName("ArchiveStatusID")
//                        .HasColumnType("int");

//                    b.Property<int?>("LessonContenetTypeId")
//                        .HasColumnName("LessonContenetTypeID")
//                        .HasColumnType("int");

//                    b.Property<string>("LessonContentDescription")
//                        .HasColumnType("varchar(50)")
//                        .HasMaxLength(50)
//                        .IsUnicode(false);

//                    b.Property<int?>("LessonOutcomeId")
//                        .HasColumnType("int");

//                    b.Property<string>("Link")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("LessonConentId");

//                    b.HasIndex("ArchiveStatusId");

//                    b.HasIndex("LessonContenetTypeId");

//                    b.HasIndex("LessonOutcomeId");

//                    b.ToTable("LessonContent");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.LessonContentType", b =>
//                {
//                    b.Property<int>("LessonContentTypeId")
//                        .HasColumnName("LessonContentTypeID")
//                        .HasColumnType("int");

//                    b.Property<string>("LessonContentDescription")
//                        .HasColumnType("varchar(50)")
//                        .HasMaxLength(50)
//                        .IsUnicode(false);

//                    b.HasKey("LessonContentTypeId");

//                    b.ToTable("LessonContentType");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.LessonOutcome", b =>
//                {
//                    b.Property<int>("LessonOutcomeId")
//                        .HasColumnName("LessonOutcomeID")
//                        .HasColumnType("int");

//                    b.Property<int?>("LessonId")
//                        .HasColumnName("LessonID")
//                        .HasColumnType("int");

//                    b.Property<string>("LessonOutcomeDescription")
//                        .HasColumnType("varchar(50)")
//                        .HasMaxLength(50)
//                        .IsUnicode(false);

//                    b.Property<string>("LessonOutcomeName")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("LessonOutcomeId");

//                    b.HasIndex("LessonId");

//                    b.ToTable("LessonOutcome");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.Onboarder", b =>
//                {
//                    b.Property<int>("OnboarderId")
//                        .HasColumnName("OnboarderID")
//                        .HasColumnType("int");

//                    b.Property<int?>("EmployeeId")
//                        .HasColumnName("EmployeeID")
//                        .HasColumnType("int");

//                    b.HasKey("OnboarderId");

//                    b.HasIndex("EmployeeId");

//                    b.ToTable("Onboarder");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.OnboarderCourseEnrollment", b =>
//                {
//                    b.Property<int>("CourseId")
//                        .HasColumnName("CourseID")
//                        .HasColumnType("int");

//                    b.Property<int?>("BadgeTotal")
//                        .HasColumnType("int");

//                    b.Property<DateTime?>("OnboarderEnrollmentDate")
//                        .HasColumnType("datetime");

//                    b.Property<DateTime?>("OnboarderGraduationDate")
//                        .HasColumnType("datetime");

//                    b.Property<int>("OnboarderId")
//                        .HasColumnName("OnboarderID")
//                        .HasColumnType("int");

//                    b.HasKey("CourseId");

//                    b.HasIndex("OnboarderId");

//                    b.ToTable("OnboarderCourseEnrollment");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.Question", b =>
//                {
//                    b.Property<int>("QuestionId")
//                        .HasColumnName("QuestionID")
//                        .HasColumnType("int");

//                    b.Property<string>("QuestionAnswer")
//                        .HasColumnType("varchar(50)")
//                        .HasMaxLength(50)
//                        .IsUnicode(false);

//                    b.Property<int?>("QuestionCategoryId")
//                        .HasColumnName("QuestionCategoryID")
//                        .HasColumnType("int");

//                    b.Property<string>("QuestionDescription")
//                        .HasColumnType("varchar(50)")
//                        .HasMaxLength(50)
//                        .IsUnicode(false);

//                    b.Property<decimal?>("QuestionMarkAllocation")
//                        .HasColumnType("numeric(18, 0)");

//                    b.Property<int?>("QuizId")
//                        .HasColumnType("int");

//                    b.HasKey("QuestionId");

//                    b.HasIndex("QuestionCategoryId");

//                    b.HasIndex("QuizId");

//                    b.ToTable("Question");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.QuestionBank", b =>
//                {
//                    b.Property<int>("QuestionBankId")
//                        .HasColumnName("QuestionBankID")
//                        .HasColumnType("int");

//                    b.Property<string>("QuestionBankDescription")
//                        .HasColumnType("varchar(50)")
//                        .HasMaxLength(50)
//                        .IsUnicode(false);

//                    b.HasKey("QuestionBankId");

//                    b.ToTable("QuestionBank");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.QuestionCategory", b =>
//                {
//                    b.Property<int>("QuestionCategoryId")
//                        .HasColumnName("QuestionCategoryID")
//                        .HasColumnType("int");

//                    b.Property<int?>("QuestionBankId")
//                        .HasColumnName("QuestionBankID")
//                        .HasColumnType("int");

//                    b.Property<string>("QuestionCategoryDescription")
//                        .HasColumnType("varchar(50)")
//                        .HasMaxLength(50)
//                        .IsUnicode(false);

//                    b.HasKey("QuestionCategoryId");

//                    b.HasIndex("QuestionBankId");

//                    b.ToTable("QuestionCategory");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.Quiz", b =>
//                {
//                    b.Property<int>("QuizId")
//                        .HasColumnName("QuizID")
//                        .HasColumnType("int");

//                    b.Property<int?>("LessonOutcomeId")
//                        .HasColumnName("LessonOutcomeID")
//                        .HasColumnType("int");

//                    b.Property<decimal?>("NumberOfQuestions")
//                        .HasColumnType("numeric(18, 0)");

//                    b.Property<DateTime?>("QuizCompletionDate")
//                        .HasColumnType("datetime");

//                    b.Property<string>("QuizDescription")
//                        .HasColumnType("varchar(50)")
//                        .HasMaxLength(50)
//                        .IsUnicode(false);

//                    b.Property<DateTime?>("QuizDueDate")
//                        .HasColumnType("datetime");

//                    b.Property<string>("QuizMarkRequirement")
//                        .HasColumnType("varchar(50)")
//                        .HasMaxLength(50)
//                        .IsUnicode(false);

//                    b.HasKey("QuizId");

//                    b.HasIndex("LessonOutcomeId");

//                    b.ToTable("Quiz");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.Title", b =>
//                {
//                    b.Property<int>("TitleId")
//                        .HasColumnName("TitleID")
//                        .HasColumnType("int");

//                    b.Property<string>("TitleDescription")
//                        .HasColumnType("varchar(50)")
//                        .HasMaxLength(50)
//                        .IsUnicode(false);

//                    b.HasKey("TitleId");

//                    b.ToTable("Title");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.AchievementType", b =>
//                {
//                    b.HasOne("BMW_ONBOARDING_SYSTEM.Models.Badge", "Badge")
//                        .WithMany("AchievementType")
//                        .HasForeignKey("BadgeId")
//                        .HasConstraintName("FK_AchievementType_Badge");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.Employee", b =>
//                {
//                    b.HasOne("BMW_ONBOARDING_SYSTEM.Models.Department", "Department")
//                        .WithMany("Employee")
//                        .HasForeignKey("DepartmentId")
//                        .HasConstraintName("FK_Employee_Department");

//                    b.HasOne("BMW_ONBOARDING_SYSTEM.Models.EmployeeCalendar", "EmployeeCalendar")
//                        .WithMany("Employee")
//                        .HasForeignKey("EmployeeCalendarId")
//                        .HasConstraintName("FK_Employee_Calendar");

//                    b.HasOne("BMW_ONBOARDING_SYSTEM.Models.Gender", "Gender")
//                        .WithMany("Employee")
//                        .HasForeignKey("GenderId")
//                        .HasConstraintName("FK_Employee_Gender");

//                    b.HasOne("BMW_ONBOARDING_SYSTEM.Models.Title", "Title")
//                        .WithMany("Employee")
//                        .HasForeignKey("TitleId")
//                        .HasConstraintName("FK_Employee_Title");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.Lesson", b =>
//                {
//                    b.HasOne("BMW_ONBOARDING_SYSTEM.Models.Course", "Course")
//                        .WithMany("Lesson")
//                        .HasForeignKey("CourseId")
//                        .HasConstraintName("FK_Lesson_Course");

//                    b.HasOne("BMW_ONBOARDING_SYSTEM.Models.LessonCompletionStatus", "LessonCompletionStatus")
//                        .WithMany("Lesson")
//                        .HasForeignKey("LessonCompletionStatusId")
//                        .HasConstraintName("FK_Lesson_LessonCompletionStatus");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.LessonContent", b =>
//                {
//                    b.HasOne("BMW_ONBOARDING_SYSTEM.Models.ArchiveStatus", "ArchiveStatus")
//                        .WithMany("LessonContent")
//                        .HasForeignKey("ArchiveStatusId")
//                        .HasConstraintName("FK_LessonContent_ArchiveStatus1");

//                    b.HasOne("BMW_ONBOARDING_SYSTEM.Models.LessonContentType", "LessonContenetType")
//                        .WithMany("LessonContent")
//                        .HasForeignKey("LessonContenetTypeId")
//                        .HasConstraintName("FK_LessonContent_LessonContentType");

//                    b.HasOne("BMW_ONBOARDING_SYSTEM.Models.LessonOutcome", "LessonOutcome")
//                        .WithMany("LessonContent")
//                        .HasForeignKey("LessonOutcomeId");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.LessonOutcome", b =>
//                {
//                    b.HasOne("BMW_ONBOARDING_SYSTEM.Models.Lesson", "Lesson")
//                        .WithMany("LessonOutcome")
//                        .HasForeignKey("LessonId")
//                        .HasConstraintName("FK_LessonOutcome_Lesson");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.Onboarder", b =>
//                {
//                    b.HasOne("BMW_ONBOARDING_SYSTEM.Models.Employee", "Employee")
//                        .WithMany("Onboarder")
//                        .HasForeignKey("EmployeeId")
//                        .HasConstraintName("FK_Onboarder_Employee");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.OnboarderCourseEnrollment", b =>
//                {
//                    b.HasOne("BMW_ONBOARDING_SYSTEM.Models.Course", "Course")
//                        .WithOne("OnboarderCourseEnrollment")
//                        .HasForeignKey("BMW_ONBOARDING_SYSTEM.Models.OnboarderCourseEnrollment", "CourseId")
//                        .HasConstraintName("FK_OnboarderCourseEnrollment_Course")
//                        .IsRequired();

//                    b.HasOne("BMW_ONBOARDING_SYSTEM.Models.Onboarder", "Onboarder")
//                        .WithMany("OnboarderCourseEnrollment")
//                        .HasForeignKey("OnboarderId")
//                        .HasConstraintName("FK_OnboarderCourseEnrollment_Onboarder")
//                        .IsRequired();
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.Question", b =>
//                {
//                    b.HasOne("BMW_ONBOARDING_SYSTEM.Models.QuestionCategory", "QuestionCategory")
//                        .WithMany("Question")
//                        .HasForeignKey("QuestionCategoryId")
//                        .HasConstraintName("FK_Question_QuestionCategory");

//                    b.HasOne("BMW_ONBOARDING_SYSTEM.Models.Quiz", "Quiz")
//                        .WithMany("Question")
//                        .HasForeignKey("QuizId");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.QuestionCategory", b =>
//                {
//                    b.HasOne("BMW_ONBOARDING_SYSTEM.Models.QuestionBank", "QuestionBank")
//                        .WithMany("QuestionCategory")
//                        .HasForeignKey("QuestionBankId")
//                        .HasConstraintName("FK_QuestionCategory_QuestionBank");
//                });

//            modelBuilder.Entity("BMW_ONBOARDING_SYSTEM.Models.Quiz", b =>
//                {
//                    b.HasOne("BMW_ONBOARDING_SYSTEM.Models.LessonOutcome", "LessonOutcome")
//                        .WithMany("Quiz")
//                        .HasForeignKey("LessonOutcomeId")
//                        .HasConstraintName("FK_Quiz_LessonOutcome");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
